### ISSUE TITLE
Ineffective if-else-statement

### ISSUE THREAD

**Issue by goergen95** [gisma/uavRst#14]
treepos at this position should be changed to variable r which was declared in line 62. Otherwise you could also get rid of line 62. I know this should not really create a bug, since most of the time some kind of raster object should be given to the function call which rasterToPoints should be able to handle. Just wanted to let you know ;)

https://github.com/gisma/uavRst/blob/5ae7564aeb1231f8c7d4b9ae0d0ffeae16b7979f/R/fa_crownseg.R#L263

**Comment by gisma** [comment]
Thanks for reporting I will fix it.

**Comment by goergen95** [comment]
Thanks for fixing that first part, but I just realized there is another issue with that function: In the vignette of chmseg_FT for treepos it is asked to supply a SpatialPointsDataFrame. To avoid confusion I would change the vignette text to ask for a raster object. Though I would even consider to include functionality to supply both, a raster or a spPointdf indicating treetops.

**Comment by gisma** [comment]
Thanks for following up. Originally it was intended to use an automatic transformation from raster to sp and vice versa than sf cam around and this process stucks. It is probably  the most consistent way is to clean the code from this relicts and provide an raster object only interface. Later on it is absolutely appreciated to implement a function that deal with this kind of data type issues. For now I will fix the text

**Comment by gisma** [comment]
uuh fix 14 was meant to be fix #16
