### ISSUE TITLE
path_run not defined in function call

### ISSUE THREAD

**Issue by goergen95** [gisma/uavRst#16]
Dear Chris,
I am not sure if I am 100% right but I think I traced back a problem I have with the pc2D_dsm-function as well as with pc2D_dtm back to this line.

https://github.com/gisma/uavRst/blob/4ec99eb72e392c97b676cb1c9efb95ebd3df1e52/R/rs_pc2D_dsm.R#L104

If call the the function like this:

dtm <- uavRst::pc2D_dtm(laspcFile = paste0(envrmt$path_data,"lidar/las_mof_aio_/"),
                        gisdbasePath = envrmt,
                        tension = 20 ,
                        sampleGridSize = 25,
                        targetGridSize = 0.5)
with laspcFile-variable linking to a directory including a bunch of las-files I will get the following error message:

Error in paste0(path_run, name) : object 'path_run' not found

I looked through the code of the function, and for me it seems that one is neither asked to set the variable path_run nor does the function retrive it from somwhere.
 Any ideas if something goes wrong on my side? Because I really can't get these functions to work right now..

Thanks for your help!

**Comment by gisma** [comment]
Thanks for pointing this out. Unfortunately nothing wrong on your side... Actually `path_run`  is a  "relict" which I obviously forgot to deal with. So using the functions  you have to create a global variable named `path_run` which is used as working directory.  I will fix it ASAP.

**Comment by goergen95** [comment]
Thanks for the information!
I got pc2D_dsm working with your suggestion, but I still struggle with pc2d_dtm.
Everytime I try to run the function, even with the standard settings I end up with the following error:

Error : XML content does not seem to be XML: 'ERROR 1: Can't load requested DLL: C:\Program Files\GDAL\gdalplugins\gdal_KEA.dll
127: Die angegebene Prozedur wurde nicht gefunden.

I think its not an issue with the function itself, but rather with my gdal installation? I already reinstalled GDAL, the dll exists in the path above and I dont think its the maximum dll error.
Any ideas how to proceed? Maybe if it helps you could check out if I got the set up of the link2GI envrionment right in the setup script:

https://github.com/GeoMOER-Students-Space/mpg-envinfosys-teams-2018-rs_18_axmideda/blob/master/src/000_env_setup.R

Thanks in advance!

**Comment by goergen95** [comment]
I just forget something. The error message is actually quiet long and in the very end I find this:

In rgrass7::initGRASS(gisBase = grass$gisbase_GRASS, home = tempdir(),  :
  working directory not writable, using tempfile for GISRC
Error in parseGRASS(cmd, legacyExec = legacyExec) : v.out.ogr not parsed

Thats why I assumed it might be a problem with the setting of the GRASS environment.

**Comment by gisma** [comment]
I think the gdal error is driven by the python script that is used in the function. Running windows it is kind of cumbersome to link Python in a correct way. 
Maybe this [blog entry](https://sandbox.idre.ucla.edu/sandbox/tutorials/installing-gdal-for-windows) is worthwhile to be checked. Another problem could be more than one gdal installation. See [r-sig-geo](https://stat.ethz.ch/pipermail/r-sig-geo/2018-November/027002.html)

**Comment by gisma** [comment]
> In rgrass7::initGRASS(gisBase = grass$gisbase_GRASS, home = tempdir(), :
working directory not writable, using tempfile for GISRC
Error in parseGRASS(cmd, legacyExec = legacyExec) : v.out.ogr not parsed

is probably linked to  rsbivand/rgrass7#4 and r-spatial/link2GI#10

Kind of confusing now: I think the `path_run`  issue is fixed. The gdal installation issue and the osgeo4W writing issues are directing to  to upper links. For me it seems more clear to discuss this issues there.  and close the `path_run`.
