### ISSUE TITLE
Error:  Creation of output file failed

### ISSUE THREAD

**Issue by goergen95** [gisma/uavRst#18]
https://github.com/gisma/uavRst/blob/c786f7a7b1e61e9151afc01831a6f04fd590815d/R/tb_bluedjinn.R#L472

The writeOGR function results in an error as well. This might be due that only the directory ```path_run``` is specified, however for writeOGR to work it needs a filename as well.

For me, this code actually resulted in no error and the creation of a output:

```rgdal::writeOGR(obj = stat, layer = "polyStat", driver = "ESRI Shapefile", dsn = paste0(path_run,"stat.shp"), overwrite_layer = TRUE)```

**Comment by gisma** [comment]
The syntax of `writeOGR()` and `readOGR()` is kind of confusing. Corresponding to the old style it means `readOGR(path, layername)` however this is not consistent as you have pointed out.  Most of the errors are related to the `path_run`  problem. In addition there is a major problem with the `GDAL` compatibility of 2.2.x and 2.3.x on both systems Windos as well as Linux. This is competeting with the needs of the cutting edge `GRASS` version. This has a simple side effect: SAGA gis is not producing any output und in a row readOGR and writeOGR will crash... Time for error handling...

**Comment by gisma** [comment]
All `pathrun/writeOGR` issues should be resolved. Please reopen if necessary.
