### ISSUE TITLE
Problems with "makeFP" on windows

### ISSUE THREAD

**Issue by LitzMar** [gisma/uavRst#2]
I am using R version 3.3.1 (2016-06-21) -- "Bug in Your Hair"
on Windows 10, release: ">= 8 x64", version "build 9200", machine: "x86-64"

problems i figuered out:
- "projectDir" needs double backslashes
- surveyArea needs as.character(c(lon, lat...))

Errors i couldn't fix:

My command:
makeFP(projectDir = "C:\\Users\\Marius\\Documents\\Uni\\Master\\WS_1617\\log_mog\\data\\proj_run", locationName = "test",
       surveyArea = as.character(c(50.840329, 8.682913)), flightAltitude = 40,
       followSurface = T, demFn = "lidar_dsm_01m.tif",
       altFilter = 1, horizonFilter = 30, flightPlanMode = "track", presetFlightTask = "remote", overlap = 0.9,
       maxSpeed = 20, maxFlightTime = 10, picRate = 2, windCondition = 1,
       uavType = "solo", cameraType = "GP3_7MP",
       dA = T)

The error:
Error in file.copy(from = surveyArea, to = file.path(projectDir, "data")) : 
  more 'from' files than 'to' files

Text of log file that is created:
[ 2017-05-18 13:52:59 ] INFO                                                             
[ 2017-05-18 13:52:59 ] INFO                                                             
[ 2017-05-18 13:52:59 ] INFO --------------------- START RUN --------------------------- 
[ 2017-05-18 13:52:59 ] INFO Working folder:  C:\Users\Marius\Documents\Uni\Master\WS_1617\log_mog\data\proj_run\/test/2017_05_18 

Thanks for your help!

**Comment by richte4d** [comment]
The survey area demands 4 input positions, each of lat long coordinates. The first 3 defining the survey area itself, the 4th is the starting point.

It looks like you put in one coordinate pair, therefore further 3 coordinate pairs are still missing


Here is a description from the uavRst package help file:

### Survey Area

To define a flight area you have to provide either 4 Points (or 3 lines). You may take more complex vectors like a multi point polygon, but only the first 4 coordinates x1, x2, x3 and x4 (for the launching position) are used in exactly this order. If you take a rectangle the 4th corner coordinate will be the launching point!

**Comment by LitzMar** [comment]
My bad, copied the wrong command.
So the command is: 
makeFP(projectDir = "C:/Users/Marius/Documents/Uni/Master/WS_1617/log_mog/data/proj_run", locationName = "test",
       surveyArea = as.character(c(50.840970, 8.683327, 50.840858, 8.683844, 50.840262, 8.683559, 50.840366, 8.682986)),
       flightAltitude = 40,
       followSurface = TRUE, demFn = "C:/Users/Marius/Documents/Uni/Master/WS_1617/log_mog/data/LIDAR/lidar_dsm_01m.tif",
       altFilter = 1, horizonFilter = 30, flightPlanMode = "track", presetFlightTask = "remote", overlap = 0.9,
       maxSpeed = 20, maxFlightTime = 10, picRate = 2, windCondition = 1,
       uavType = "solo", cameraType = "GP3_7MP",
       dA = TRUE)

Error keeps the same:
Error in file.copy(from = surveyArea, to = file.path(projectDir, "data")) : 
  more 'from' files than 'to' files

**Comment by gisma** [comment]
fixed and moved to uavRmp
