### ISSUE TITLE
lidR reverse dependency check

### ISSUE THREAD

**Issue by Jean-Romain** [gisma/uavRst#20]
Hi,

`uavRst` (CRAN version) depends (in suggest field) on `lidR`. I planned to release lidR 2.0.0 before to have any dependency but too late... I [searched in the source code](https://github.com/cran/uavRst/search?l=R&q=lidR) to find occurrence of lidR. I found only  few occurrences of `readLAS`, `writeLAS` and `lasclipRectangle`. Reading the code it seems ok, your code should still work with the new release. 

I also ran a revert dependency check but `devtools` changed and the new package `revdepcheck` provide a non-useful output

```
# Platform

|field    |value                        |
|:--------|:----------------------------|
|version  |R version 3.5.1 (2018-07-02) |
|os       |Linux Mint 18.3              |
|system   |x86_64, linux-gnu            |
|ui       |RStudio                      |
|language |(EN)                         |
|collate  |fr_CA.UTF-8                  |
|ctype    |fr_CA.UTF-8                  |
|tz       |America/Toronto              |
|date     |2018-12-21                   |

# Dependencies

|package |old   |new |Δ  |
|:-------|:-----|:---|:--|
|lidR    |1.6.1 |NA  |*  |

# Revdeps

## Couldn't check (1)

|package |version |error |warning |note |
|:-------|:-------|:-----|:-------|:----|
|uavRst  |?       |      |        |     |

## All (1)

|package |version |error |warning |note |
|:-------|:-------|:-----|:-------|:----|
|uavRst  |?       |      |        |     |
```

  Could you confirm that I will not break your current release with the update of lidR.

Cheers

**Comment by gisma** [comment]
Jean-Romain 
confirmed. I took most of the lidR 1.x  code out. For the next release I am substituting  all functions dealing with LiDAR  according to lidR 2.x
Thanks for pointing out.
Cheers Chris

**Comment by Jean-Romain** [comment]
I made a manual check. I found 1 NOTE

```
* checking dependencies in R code ... NOTE
Missing or unexported object: ‘lidR::extent’
```

I can't find any code related to `lidR::extent` in the released code. Any hint ?

**Comment by Jean-Romain** [comment]
Ok I found two occurrences with `grep` . Github search engine is definitively poor. I must fix that by reintroducing temporarily  the method `lidR::extent`. If such code still appears in the development version, please change it by `raster::extent`.

**Comment by Jean-Romain** [comment]
I also found the following line that have been silently skipped. Probably not called in any example or unit test. The function `treepos_lidR` will fail if called. Hopefully it is not called.

```r
localmaxima <- lidR::tree_detection(x = chm, ws=movingWin, hmin = minTreeAlt)
```

You must rewrite your code L259-260 in `fa_treetops.R` in your `develop` branch
