### ISSUE TITLE
make_lidr_catalog - function is not exported to namespace in develop branch

### ISSUE THREAD

**Issue by goergen95** [gisma/uavRst#21]
https://github.com/gisma/uavRst/blob/a3bf161d3dbbf86e30b862a2859d55f73026efe3/NAMESPACE#L21

Hi!
I recently run into an issue while trying to use the very useful lidr_catalog function in your packages while having installed the develop-branch of this repo.  It is actually not exported to the namespace of the packages. This is also the case for the version which is available via cran.
If it isn't on purpose that you want to get rid of the function would you mind fixing it here on the develop branch as well later on cran?
Thanks in adavance!
Regards,
Darius.

**Comment by gisma** [comment]
dropped function
