### ISSUE TITLE
Wrong output path

### ISSUE THREAD

**Issue by SchoenbergA** [gisma/uavRst#22]
Hi Gisma,

while running the useful lidR (v2) code (from the wiki) to compute ditigal terrain models, i run into an issue.

https://github.com/gisma/uavRst/blob/234fb15050dcf27262f371a06f34628a02266f27/R/rs_lidr_makros.R#L39

the corrected las files are stored on the wrong path wehn using own folder structur.
eg: i have folderstr: test/las/  (with org las files)
                                test/las/example/

when using the code the output will be generated in the test folder and not the subfolders.
So the output las data is not in the set path0.
Same problem is with further functions: the returning data is saved in the wrong  #folders

Help would be nice.

**Comment by gisma** [comment]
fixed
