### ISSUE TITLE
Got an error running function chmseg_GWS()

### ISSUE THREAD

**Issue by hyang419** [gisma/uavRst#25]
Hi,
I have a question regarding the error message I got from running function chmseg_GWS(). I installed all the packages needed. Saw this error came out: 

![grasserror](https://user-images.githubusercontent.com/71274521/135473092-f2ba60d8-820b-4c7b-a759-7a8648a10c01.PNG)

Do you know what that means and thank you for reading!

**Comment by gisma** [comment]
Hallo hyang419, actually I need your sessionInfo for debugging it. Obviously You have installed `GRASS` via QGIS. I recommend updating QGIS to the current LTS. Even better install the most recent stable GRASS version  standalone or via OSGEO4W
best Chris
