### ISSUE TITLE
makeFP status 127

### ISSUE THREAD

**Issue by Ludwigm6** [gisma/uavRst#3]
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

After the successfull creation of a flightplan with makeFP() I get the message:
.
.
.
 NOTE 1:  Have Fun   
 NOTE 2: You will find all parameters in the logfile: D:/caldern/uav/fp_lahn/2017_05_20/logfp_lahn_40m_solo_MAPIR2_survey_area_lahn_2017_05_20_16-53.log  
 
Warning message:
running command 'rm -rf D:/caldern/uav/fp_lahn/2017_05_20/run' had status 127

**Comment by gisma** [comment]
fixed and moved to uavRmp
